version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acadêmicas
  - aceitos
  - Aceitos
  - Acesso
  - acumulados
  - agrupamento
  - Agrupar
  - ainda
  - algumas
  - Alterações
  - alterado
  - Alteravel
  - andamento
  - Andamento
  - apenas
  - Apenas
  - arquivo
  - Arquivo
  - assim
  - atual
  - Atualiza
  - atualização
  - atualizada
  - Atualizada
  - atualizado
  - autenticado
  - Autenticado
  - automático
  - baseada
  - Botão
  - cada
  - cadastrada
  - Cadastradas
  - cadastrando
  - Cadastrando
  - cadastrar
  - Cadastrar
  - Cadastro
  - Calcular
  - Cálculo
  - cancelar
  - Cancelar
  - caracteres
  - carregando
  - Carregando
  - categorias
  - classificacao
  - classificação
  - Classificação
  - coincidem
  - Coluna
  - competencia
  - Competencia
  - competência
  - Competência
  - Competências
  - completo
  - Completo
  - Complto
  - concluídas
  - concluido
  - Concluído
  - conexao
  - conexão
  - Configuração
  - confirmar
  - Confirmar
  - Corrigir
  - credenciais
  - Descreva
  - descricao
  - Descrição
  - detalhes
  - Determinação
  - Determinar
  - deve
  - dicas
  - Dicas
  - digite
  - Digite
  - Distribuição
  - documentos
  - Doutorado
  - elemento
  - Entrar
  - escolaridade
  - Escolaridade
  - ESCOLARIDADES
  - Escolha
  - especialidade
  - especialização
  - específica
  - etapa
  - etapas
  - Etapas
  - facilitar
  - Falha
  - Falhou
  - fazer
  - fechar
  - Fechar
  - forem
  - Garantir
  - geral
  - Gerencie
  - graduação
  - Graduação
  - imediato
  - Importantes
  - incompleto
  - informações
  - inicial
  - Início
  - Instituicao
  - Invalido
  - inválido
  - itens
  - joao
  - João
  - levar
  - Mantenha
  - matricula
  - Matrícula
  - médio
  - menos
  - Mestrado
  - mínimos
  - mockada
  - muito
  - Muito
  - necessidade
  - negada
  - Negada
  - nenhuma
  - Nenhuma
  - nível
  - número
  - Obrigatoria
  - obrigatória
  - Opcional
  - organizados
  - pendente
  - Pendente
  - Perfil
  - periodo
  - Período
  - permissao
  - Permissão
  - pessoais
  - pode
  - pontos
  - Pontos
  - Pontuacao
  - Pontuação
  - preenchimento
  - Preenchimento
  - profissionais
  - profissional
  - progresso
  - Próximo
  - quantidade
  - Quantidade
  - realizada
  - realizado
  - Realizado
  - Receber
  - Recentes
  - Reconhecimento
  - registrada
  - Registradas
  - Registre
  - registro
  - Registro
  - removida
  - Removida
  - requisitos
  - resumo
  - Resumo
  - Saberes
  - sair
  - Sair
  - Salvando
  - Salvar
  - Selecione
  - semanas
  - senha
  - Senha
  - senhas
  - servidor
  - seus
  - subtitulo
  - sucesso
  - Tecnólogo
  - tipo
  - Tipo
  - titulo
  - Última
  - únicas
  - Unitario
  - Unitário
  - Validacao
  - validação
  - válido
  - Verificação
  - Verifique
  - Visão
ignoreWords: []
import: []
