// Centralização de textos do sistema

export const LABELS = {
  atividade: 'Atividade',
  documento: 'Documento comprobatório',
  quantidade: 'Quantidade',
  dataInicio: 'Data de Início',
  dataFim: 'Data de Fim',
  observacoes: 'Observações',
  registrar: 'Registrar',
  registrarNovaAtividade: 'Registrar Nova Atividade',
  menu: 'Menu',
  dashboard: 'Dashboard',
  registrarAtividade: 'Registrar Atividade',
  sistemaTitulo: 'Sistema de Competências',
  login: 'Login',
  sair: 'Sair',
  selecioneUmaAtividade: 'Selecione uma atividade',
  criterio: 'Critério de Pontuação',
  documentoObrigatorio: 'Documento Obrigatório',
  documentoComprobatorio: 'Documento Comprobatório',
  pontuacaoEstimada: 'Pontuação Estimada',
  pontos: 'pontos',
  informacoesAdicionaisSobreAtividade: 'Informações adicionais sobre a atividade (opcional)',
  descricao: 'Descrição',
  tipoCalculo: 'Tipo de Cálculo',
  unidadeMedida: 'Unidade de Medida',
  valorPonto: 'Valor por Unidade',
  documentosComprobatorios: 'Documentos Comprobatórios',
  // Adicione outros textos conforme necessário
}; 